[package]
name = "PICO_SSD1351_DRIVER"
description = "A driver created for the SSD1351 OLED 1.5 inch rgb screen for the Pi Pico W"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
